server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wanglei5413/microservicecloud-config.git #GitHub上面的git仓库名字
          #uri: git@github.com:wanglei5413/microservicecloud-config.git 